# Generated by Django 4.2.7 on 2026-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('product_assist', 'Product Assistance'), ('store_generator', 'Store Generator')], max_length=50)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
