# Generated by Django 4.2.7 on 2026-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
